 platform :ios, '10.0'

target 'InterfaithIt' do

  use_frameworks!

  # Pods for InterfaithIt
pod 'SDWebImage', '~> 5.0'
pod 'GoogleAPIClientForREST/Sheets', '~> 1.2.1'
pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
pod 'GoogleSignIn'
pod 'MXLCalendarManagerSwift'
pod 'Alamofire', '4.8.1'
pod 'SwiftSoup'

  target 'InterfaithItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterfaithItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
