 platform :ios, '8.0'

target 'ReligiousApp' do

  use_frameworks!

  # Pods for ReligiousApp
pod 'SDWebImage', '~> 5.0'

  target 'ReligiousAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReligiousAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
